---
- hosts: localhost
  gather_facts: yes
  vars:
    rpi_hostname: rpidus.redhat.com
  vars_files:
    - /root/rpi_garage_door_opener_vars.yml
  roles:
    - { role: ansible-role-basic_setup }
    - { role: ansible-role-umts_usb_stick }
    - { role: ansible-role-check_network_connection }
    - { role: ansible-role-ssh_tunnel }
    - { role: ansible-role-wiringpi }
    - { role: ansible-role-webiopi }
    - { role: ansible-role-watchdog }
    - { role: ansible-role-postfix }
    - { role: ansible-role-arpwatch }
