---
# tasks file for role basic_info

- name: Ensure required packages are installed
  package:
    name: postfix,cyrus-sasl-plain,mailx
    state: present
  tags: postfix

- name: Copy postfix sasl config 
  template:
    src: sasl_passwd.jp2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  tags: postfix

- name: Copy postfix tls config 
  template:
    src: tls_policy.jp2
    dest: /etc/postfix/tls_policy
    mode: 0600
  tags: postfix

- name: Create sasl hash db file
  command:
    cmd: "postmap /etc/postfix/sasl_passwd"
  tags: postfix

- name: Create tls hash db file
  command:
    cmd: "postmap /etc/postfix/tls_policy"
  tags: postfix

- name: Update postfix config
  lineinfile:
    path: /etc/postfix/main.cf
    insertafter: "^#relayhost.*"
    line: "relayhost = [smtp.gmail.com]:587"
  tags: postfix

- name: Update posfix config
  lineinfile:
    path: /etc/postfix/main.cf
    insertafter: "^#myhostname.*"
    line: "myhostname = {{ rpi_hostname }}"
  tags: postfix

- name: Update postfix config - SASL
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SASL"
    backup: yes
    block: |
      # Enable TLS authentication
      smtp_use_tls = yes
      # Enable SASL authentication
      smtp_sasl_auth_enable = yes
      # # Allow methods that allow anonymous authentication
      smtp_sasl_security_options =
      # # Allow methods that allow anonymous authentication
      smtp_sasl_tls_security_options =
      # Location of sasl_passwd
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      # Location of tls password
      smtp_tls_policy_maps = hash:/etc/postfix/tls_policy
      # Enable STARTTLS encryption
      smtp_tls_security_level = encrypt
      # Location of CA certificates
      #smtp_tls_CAfile = /etc/pki/tls/cert.pem
      smtp_tls_CAfile = /etc/ssl/certs/ca-bundle.crt
  tags: postfix

- name: Force systemd to reread config, enable and start service
  systemd:
    name: postfix
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: postfix
