---
# tasks file for role basic_info

- name: Ensure required packages are installed
  package:
    name: postfix
    state: present
  tags: postfix

- name: Copy postfix config 
  template:
    src: sasl_passwd.jp2
    dest: /etc/postfix/sasl/sasl_passwd
    mode: 0600
  tags: postfix

- name: Create hash db file
  command:
    cmd: "postmap /etc/postfix/sasl/sasl_passwd"
  tags: postfix

- name: Update posfix config
  lineinfile:
    path: /etc/postfix/main.cf
    insertafter: "^#relayhost.*"
    line: "relayhost = [smtp.gmail.com]:587"
  tags: postfix

- name: Update postfix config - SASL
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SASL"
    backup: yes
    block: |
      # Enable SASL authentication
      smtp_sasl_auth_enable = yes
      # # Disallow methods that allow anonymous authentication
      smtp_sasl_security_options = noanonymous
      # # Location of sasl_passwd
      smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd
      # # Enable STARTTLS encryption
      smtp_tls_security_level = encrypt
      # # Location of CA certificates
      smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
  tags: postfix

- name: Force systemd to reread config, enable and start service
  systemd:
    name: postfix
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: postfix
